name: App Deployment
on: 
    push: 
        branches: 
            - master
        tags: 
          - "v*"
jobs: 
    run-deployment: 
        runs-on: ubuntu-latest
        steps: 
            - name: "Checkouts out from the repository 1"
              uses: actions/checkout@v4

            - name: "Build the image"
              run: |
                docker build -t theoafactor/conflag_deploy_test:v1.0.0 .

            - name: "Login into Docker HUb"
              run: | 
                docker login -u theoafactor -p ${{ secrets.DOCKERHUB_PASSWORD }} 
                
            - name: "Push the image to Docker Hub"
              run: |
                docker push theoafactor/conflag_deploy_test:v1.0.0

            - name: Extract Version from Tag
              id: extract_version
              run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

            - name: Clone Helm Repository
              run: |
                git clone https://github.com/theoafactor/conflaga_h.git conflaga_h
                cd conflaga
                git config user.name "Olu Adeyemo"
                git config user.email "theoafactor@gmail.com"

            - name: Update Helm Chart Version
              run: |
                  cd conflaga
                  sed -i "s/^version: .*/version: ${{ env.version }}/" <path-to-Chart.yaml>
                  sed -i "s/^appVersion: .*/appVersion: ${{ env.version }}/" <path-to-Chart.yaml>




