name: App Deployment
on: 
    push: 
        branches: 
            - master
jobs: 
    run-deployment: 
        runs-on: ubuntu-latest
        steps: 
            - name: "Checkouts out from the repository 1"
              uses: actions/checkout@v4

            - name: "Build the image"
              run: |
                docker build -t theoafactor/conflag_deploy_test:v1.0.0 .

            - name: "Login into Docker HUb"
              run: | 
                docker login -u theoafactor -p ${{ secrets.DOCKERHUB_PASSWORD }} 
                
            - name: "Push the image to Docker Hub"
              run: |
                docker push theoafactor/conflag_deploy_test:v1.0.0





